# Generated by Django 6.0.6 on 2026-06-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('partner_name', models.CharField(max_length=100, verbose_name='Имя партнера')),
                ('short_description', models.TextField(verbose_name='Краткое описание (в карточке)')),
                ('full_description', models.TextField(verbose_name='Подробное описание (в модалке)')),
                ('link', models.URLField(verbose_name='Ссылка на сайт партнера')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество предложений')),
                ('image', models.ImageField(upload_to='offers/', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='partners.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Партнерское предложение',
                'verbose_name_plural': 'Партнерские предложения',
            },
        ),
    ]
