# Generated by Django 6.0.6 on 2026-06-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='partneroffer',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество предложений'),
        ),
        migrations.AlterField(
            model_name='partneroffer',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='partneroffer',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Подробное описание (в модалке)'),
        ),
        migrations.AlterField(
            model_name='partneroffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='partneroffer',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт партнера'),
        ),
        migrations.AlterField(
            model_name='partneroffer',
            name='partner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя партнера'),
        ),
        migrations.AlterField(
            model_name='partneroffer',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (в карточке)'),
        ),
        migrations.AlterField(
            model_name='partneroffer',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='partneroffer',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
